"""Create User and OutstandingToken models

Revision ID: 228071870c45
Revises: 
Create Date: 2022-07-10 07:29:34.465061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228071870c45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_user_email'), 'user', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_user_id'), 'user', ['id'], unique=False, schema='users')
    op.create_table('outstanding_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_outstanding_token_id'), 'outstanding_token', ['id'], unique=False, schema='users')
    op.create_index(op.f('ix_users_outstanding_token_jti'), 'outstanding_token', ['jti'], unique=True, schema='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_outstanding_token_jti'), table_name='outstanding_token', schema='users')
    op.drop_index(op.f('ix_users_outstanding_token_id'), table_name='outstanding_token', schema='users')
    op.drop_table('outstanding_token', schema='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='user', schema='users')
    op.drop_index(op.f('ix_users_user_email'), table_name='user', schema='users')
    op.drop_table('user', schema='users')
    # ### end Alembic commands ###
