"""Update user model

Revision ID: 52b8a7f18ef5
Revises: bdd884eb3e67
Create Date: 2022-07-16 06:57:19.687966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '52b8a7f18ef5'
down_revision = 'bdd884eb3e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True), schema='users')
    op.add_column('user', sa.Column('avatar', sa.String(), nullable=True), schema='users')
    op.add_column('user', sa.Column('uae_id', sa.String(length=100), nullable=True), schema='users')
    op.add_column('user', sa.Column('passport_id', sa.String(length=100), nullable=True), schema='users')
    op.add_column('user', sa.Column('street', sa.String(length=100), nullable=True), schema='users')
    op.add_column('user', sa.Column('city', sa.String(length=100), nullable=True), schema='users')
    op.add_column('user', sa.Column('country', sa.String(length=100), nullable=True), schema='users')
    op.add_column('user', sa.Column('state', sa.String(length=100), nullable=True), schema='users')
    op.add_column('user', sa.Column('instagram_url', sa.String(), nullable=True), schema='users')
    op.add_column('user', sa.Column('height', sa.Float(), nullable=True), schema='users')
    op.add_column('user', sa.Column('weight', sa.Float(), nullable=True), schema='users')
    op.add_column('user', sa.Column('zip_code', sa.String(length=100), nullable=True), schema='users')
    
    busttype_enum = postgresql.ENUM('NATURAL', 'IMPLANTS', name='busttype')
    busttype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('bust_type', busttype_enum, nullable=True), schema='users')
    
    op.create_unique_constraint(None, 'user', ['avatar'], schema='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='users', type_='unique')
    op.drop_column('user', 'bust_type', schema='users')
    op.drop_column('user', 'zip_code', schema='users')
    op.drop_column('user', 'weight', schema='users')
    op.drop_column('user', 'height', schema='users')
    op.drop_column('user', 'instagram_url', schema='users')
    op.drop_column('user', 'state', schema='users')
    op.drop_column('user', 'country', schema='users')
    op.drop_column('user', 'city', schema='users')
    op.drop_column('user', 'street', schema='users')
    op.drop_column('user', 'passport_id', schema='users')
    op.drop_column('user', 'uae_id', schema='users')
    op.drop_column('user', 'avatar', schema='users')
    op.drop_column('user', 'birth_date', schema='users')
    # ### end Alembic commands ###
