"""Create BlacklistToken model

Revision ID: bdd884eb3e67
Revises: 228071870c45
Create Date: 2022-07-10 07:46:49.135375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd884eb3e67'
down_revision = '228071870c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outstanding_token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['outstanding_token_id'], ['users.outstanding_token.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_blacklist_token_id'), 'blacklist_token', ['id'], unique=False, schema='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_blacklist_token_id'), table_name='blacklist_token', schema='users')
    op.drop_table('blacklist_token', schema='users')
    # ### end Alembic commands ###
